# Generated by Django 4.2.13 on 2024-07-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_is_admin_myuser_phone_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='token_expiry_time',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
