# Generated by Django 4.2.13 on 2024-07-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_myuser_token_expiry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role_id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Read Only'), (2, 'Read and Edit'), (3, 'Admin')], default=1),
        ),
    ]
