# Generated by Django 4.2.13 on 2024-07-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tokenblacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role_id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Read Only'), (2, 'Read and Edit'), (3, 'Admin')]),
        ),
    ]
