# Generated by Django 4.2.13 on 2024-07-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_myuser_role_id_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Read Only'), ('editor', 'Read and Edit'), ('admin', 'Admin')], max_length=20),
        ),
    ]
