

# # response messages

# # Admin
# ADMIN_LOGIN_INVALID_CRED = "ADMIN_LOGIN_INVALID_CRED"
# ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"
# ADMIN_EMAIL_ALREADY_EXISTS = 'ADMIN_EMAIL_ALREADY_EXISTS'
# ALARM_COUNT_SUCCESSFULLY = 'ALARM_COUNT_SUCCESSFULLY'
INVALID_REQUEST = "INVALID_REQUEST"
# ALLOWED_SITE_COUNT_THRESHOLD_EXCEEDED = "ALLOWED_SITE_COUNT_THRESHOLD_EXCEEDED"
TOKEN_EXPIRED = "TOKEN_EXPIRED"
UNAUTHORISED_ACCESS = "ACCESS_DENIED"
# USER_PROFILE_UPDATED_SUCCESSFULLY = "USER_PROFILE_UPDATED_SUCCESSFULLY"
# USER_DELETED_SUCCESSFULLY = "USER_DELETED_SUCCESFULLY"
# AUDIT_LOGS_DELETED_SUCCESFULLY = "AUDIT_LOGS_DELETED_SUCCESFULLY"
# ROLE_CREATED_SUCCESSFULLY = "ROLE_CREATED_SUCCESSFULLY"
# ROLE_UPDATED_SUCCESSFULLY = "ROLE_IS_BEING_UPDATED"
# ROLE_DELETED_SUCCESSFULLY = "ROLE_DELETED_SUCCESSFULLY"
# ERROR_IN_ROLE_DELETION = "ERROR_IN_ROLE_DELETION"
# ROLE_LISTED_SUCCESSFULLY = "ROLE_PERMISSION_LISTED_SUCCESSFULLY"
# ERROR_IN_UPDATING_THE_ROLE = "ERROR_IN_UPDATING_THE_ROLE"
# ERROR_IN_LISTING_THE_ROLE = "ERROR_IN_LISTING_THE_ROLE"
# ROLE_DELETED_WITH_ERRORS = "ROLE_DELETED_WITH_ERRORS"
# ASSIGNED_ROLE = 'CANNOT_DELETE_ASSIGNED_ROLE'
# ERROR_IN_FETCHING_DATA = "ERROR_IN_FETCHING_DATA"
# NO_DATA_AVAILABLE = "NO_DATA_AVAILABLE"
# ADMIN_UPDATED_SUCCESSFULLY = 'ADMIN_UPDATED_SUCCESSFULLY'
# ADMIN_UPDATE_EXCEPTION = 'EXCEPTION_OCCURED_WHILE_UPDATING_ADMIN'
# ADMIN_UPDATE_ERROR = 'ERROR_OCCURED_WHILE_UPDATING_ADMIN'


# # Sites
# SITE_LISTED_SUCCESSFULLY = "SITE_LISTED_SUCCESSFULLY"
# SITE_ADDED_SUCCESSFULLY = "SITE_ADDED_SUCCESSFULLY"
# SITE_UPDATED_SUCCESSFULLY = "SITE_UPDATED_SUCCESSFULLY"
# SITE_RADIO_RETRIEVED_SUCCESSFULLY = "SITE_RADIO_RETRIEVED_SUCCESSFULLY"
# SITE_RADIO_UPDATED_SUCCESSFULLY = "SITE_RADIO_UPDATED_SUCCESSFULLY"
# COUNTRY_LISTED_SUCCESSFULLY = "COUNTRY_LISTED_SUCCESSFULLY"
# SITE_DELETED_SUCCESSFULLY = "SITE_DELETED_SUCCESSFULLY"
# SITE_DOESNOT_EXISTS = 'SITE_DOESNOT_EXISTS'
# SITE_DATA_COUNT_LISTED_SUCCESSFULLY = 'SITE_DATA_COUNT_LISTED_SUCCESSFULLY'
# SITE_DELETED_WITH_ERRORS = "SITE_DELETED_WITH_ERRORS"
# NAT_ACCESS_POINT_AND_NAT_AP_GROUP_STATUS_COUNTED_SUCCESSFULLY = "NAT_ACCESS_POINT_AND_NAT_AP_GROUP_STATUS_COUNTED_SUCCESSFULLY"
# SITE_DETAILS_LISTED_SUCCESSFULLY = "SITE_DETAILS_LISTED_SUCCESSFULLY"

# # ATPC
# ATPC_CONFIGURATION_LISTED = "ATPC Configuration listed successfully"
# ATPC_CONFIGURATION_LIST_ERROR = "Error while listing the ATPC data"
# ATPC_CONFIGURATION_UPDATED = "ATPC Configuration Data updated successfully"
# ATPC_CONFIGURATION_UPDATE_EXCEPTION = "Error while updating the ATPC data"

# # ALARMS
# ALARM_CONFIGURATION_LISTED_SUCCESSFULLY = "ALARM_CONFIGURATION_LISTED_SUCCESSFULLY"
# ALARM_CONFIGURATION_UPDATED_SUCCESSFULLY = "ALARM_CONFIGURATION_UPDATED_SUCCESSFULLY"
# ALARM_DAMP_CONFIG_LISTED_SUCCESSFULLY = "ALARM_DAMP_CONFIG_LISTED_SUCCESSFULLY"
# ALARM_DAMP_CONFIG_UPDATED_SUCCESSFULLY = "ALARM_DAMP_CONFIG_UPDATED_SUCCESSFULLY"
# ALARM_ACKNOWLEDGED_SUCCESSFULLY = "ALARM_ACKNOWLEDGED_SUCCESSFULLY"
# DEFAULT_ALARMS_EMAIL_LISTED_SUCCESSFULLY ='DEFAULT_ALARMS_EMAIL_LISTED_SUCCESSFULLY'
# DEFAULT_ALARMS_EMAIL_LIST = "EXCEPTION_OCCURED_WHILE_LISTING_DEFAULT_ALARMS_EMAIL"
# NTP_UPDATE_EXECPTION = 'EXCEPTION_OCCURED_WHILE_UPDATING_NTP'

# # Devices
# ACCESS_POINT_ADDED_SUCCESSFULLY = "ACCESS_POINT_ADDED_SUCCESSFULLY"
# ACCESS_POINT_UPDATED_SUCCESSFULLY = "ACCESS_POINT_UPDATED_SUCCESSFULLY"
# ACCESS_POINT_DELETED_SUCCESSFULLY = "DEVICES_DELETION_INITIATED_SUCCESSFULLY"
# ACCESS_POINT_LISTED_SUCCESSFULLY = "ACCESS_POINT_LISTED_SUCCESSFULLY"
# ACCESS_POINT_RADIO_RETRIEVED_SUCCESSFULLY = "ACCESS_POINT_RADIO_RETRIEVED_SUCCESSFULLY"
# ACCESS_POINT_RADIO_UPDATED_SUCCESSFULLY = "ACCESS_POINT_RADIO_UPDATED_SUCCESSFULLY"
# ACCESS_POINT_STATUS_COUNTED_SUCCESSFULLY = "ACCESS_POINT_STATUS_COUNTED_SUCCESSFULLY"
# ALARM_COUNTED_SUCCESSFULLY = "ALARM_COUNTED_SUCCESSFULLY"
# CLIENT_COUNTED_SUCCESSFULLY = "CLIENT_COUNTED_SUCCESSFULLY"
# INTERFACE_PER_MODEL_LISTED_SUCCESSFULLY = "INTERFACE_PER_MODEL_LISTED_SUCCESSFULLY"
# AP_NAME_ALREADY_EXISTS = "AP_NAME_ALREADY_EXISTS"
# DEVICE_DOESNOT_EXISTS = "DEVICE_DOESNOT_EXISTS"
# INVALID_IP_v4 = "INVALID_IP_v4"
# INVALID_IP_v6 = "INVALID_IP_v6"
# IPv4_ALREADY_EXISTS = "IPv4_ALREADY_EXISTS"
# IPv6_ALREADY_EXISTS = "IPv6_ALREADY_EXISTS"
# NO_IP_WITH_DHCP = "NO_IP_WITH_DHCP_ENABLED"
# NO_IP_WITH_NAT = "NO_IP_WITH_NAT_DISABLED"
# AP_MODEL_LISTED_SUCCESSFULLY = "AP_MODEL_LISTED_SUCCESSFULLY"
# DEVICE_STATUS_LISTED_SUCCESSFULLY = "DEVICE_STATUS_LISTED_SUCCESSFULLY"

# # commonly used Macros
# STATUS_CODE = {"IS_ENABLED": 1, "IS_DISABLED": 0, "IS_DELETED": 2}

# # Global SSID
# GLOBAL_SSID_ADDED_SUCCESSFULLY = "GLOBAL_SSID_ADDED_SUCCESSFULLY"
# GLOBAL_SSID_UPDATED_SUCCESSFULLY = "GLOBAL_SSID_UPDATED_SUCCESSFULLY"
# GLOBAL_SSIDS_DELETED_SUCCESSFULLY = "GLOBAL_SSIDS_DELETED_SUCCESSFULLY"

# # AP SSID
# SSID_ADDED_SUCCESSFULLY = "SSID_ADDED_SUCCESSFULLY"
# SSID_UPDATED_SUCCESSFULLY = "SSID_UPDATED_SUCCESSFULLY"
# SSID_DELETED_SUCCESSFULLY = "SSID_DELETED_SUCCESSFULLY"
# SSID_DELETED_WITH_ERRORS = "SSID_DELETED_WITH_ERRORS"

# # AP CLI USERS
# AP_CLI_USER_CREATED_SUCCESSFULLY = "AP_CLI_USER_CREATED_SUCCESSFULLY"
# AP_CLI_USER_UPDATED_SUCCESSFULLY = "AP_CLI_USER_UPDATED_SUCCESSFULLY"
# AP_CLI_USER_CREATE_ERROR = "AP_CLI_USER_CREATE_ERROR"
# AP_CLI_USER_DELTED_SUCCESSFULLY = "AP_CLI_USER_DELTED_SUCCESSFULLY"
# AP_ASSOCIATED_WITH_SITE_ERRORS = 'AP_ASSOCIATED_WITH_SITE_ERRORS'

# # WIPS
# WIPS_CONFIG_UPDATED_SUCCESSFULLY = "WIPS_CONFIG_UPDATED_SUCCESSFULLY"
# WIPS_CONFIG_RETRIEVED_SUCCESSFULLY = "WIPS_CONFIG_RETRIEVED_SUCCESSFULLY"
# WIPS_CONFIG_CREATED_SUCCESSFULLY = "WIPS_CONFIG_CREATED_SUCCESSFULLY"
# WIPS_CONFIG_DELETED_SUCCESSFULLY = "WIPS_CONFIG_DELETED_SUCCESSFULLY"

# # EOGRE
# EOGRE_PROFILE_CREATED = "EOGRE_PROFILE_CREATED_SUCESSFULLY"
# EOGRE_PROFILE_UPDATED = "EOGRE_PROFILE_UPDATED_SUCCESSFULLY"
# EOGRE_PROFILE_DELETED = "EOGRE_PROFILE_DELETED_SUCCESSFULLY"
# SSID_COUNTED_SUCCESSFULLY = "SSID_COUNTED_SUCCESSFULLY"

# # EOIP
# EOIP_PROFILE_CREATED = "EOIP_PROFILE_CREATED_SUCESSFULLY"
# EOIP_PROFILE_UPDATED = "EOIP_PROFILE_UPDATED_SUCCESSFULLY"
# EOIP_PROFILE_DELETED = "EOIP_PROFILE_DELETED_SUCCESSFULLY"

# # Captive portal profile
# CAPTIVE_PORTAL_PROFILE_ADDED_SUCCESSFULLY = "CAPTIVE_PORTAL_PROFILE_ADDED_SUCCESSFULLY"
# CAPTIVE_PORTAL_PROFILE_UPDATED_SUCCESSFULLY = (
#     "CAPTIVE_PORTAL_PROFILE_UPDATED_SUCCESSFULLY"
# )
# CAPTIVE_PORTAL_PROFILE_DELETED_SUCCESSFULLY = (
#     "CAPTIVE_PORTAL_PROFILE_DELETED_SUCCESSFULLY"
# )

# # L4 & L7 Identification
# L4_L7_UPDATED_SUCCESSFULLY = "L4_L7_UPDATED_SUCCESSFULLY"

# # SystemConfig
# SYSTEM_CONIFG_LISTED_SUCCESSFULLY = "SYSTEM_CONIFG_LISTED_SUCCESSFULLY"
# SYSTEM_CONIFG_UPDATED_SUCCESSFULLY = "SYSTEM_CONIFG_UPDATED_SUCCESSFULLY"
# SYSTEM_LOGO_UPLOADED_SUCCESSFULLY = "SYSTEM_LOGO_UPLOADED_SUCCESSFULLY"
# UBR_SYSTEM_CONIFG_UPDATED_SUCCESSFULLY = "UBR_SYSTEM_CONIFG_UPDATED_SUCCESSFULLY"
# DEVICE_PASSWORD_AGE_UPDATED_SUCCESSFULLY = 'DEVICE_PASSWORD_AGE_UPDATED_SUCCESSFULLY'
# PASSWORD_AGE_UPDATE_EXECPTION = 'Exception occurred while updating Device Password Age'

# # NATConfig
# NAT_Config_CREATED = "NAT_Config_CREATED_SUCCESSFULLY"
# NAT_Config_UPDATED = "NAT_Config_UPDATED_SUCCESSFULLY"
# NAT_Config_DELETED = "NAT_Config_DELETED_SUCCESSFULLY"

# # AP logs utils
# FILE_NOT_SUBMITTED = "FILE_NOT_SUBMITTED"
# FILE_IS_EMPTY = "FILE_IS_EMPTY"

# ERROR_IN_FINDING_SSID_COUNT_DETAILS = "ERROR_IN_FINDING_SSID_COUNT_DETAILS"

# # Tenant
# TENANT_ADDED_SUCCESSFULLY = 'TENANT_ADDED_SUCCESSFULLY'
# TENANT_ACTIVATED_SUCCESSFULLY = "TENANT_ACTIVATED_SUCCESSFULLY"
# TENANT_DEACTIVATED_SUCCESSFULLY = "TENANT_DEACTIVATED_SUCCESSFULLY"
# TENANT_UPDATED_SUCCESSFULLY = "TENANT_UPDATED_SUCCESSFULLY"
# TENANT_RETRIEVED_SUCCESSFULLY = "TENANT_RETRIEVED_SUCCESSFULLY"

# # Report
# REPORT_ADDED_SUCCESSFULLY = "REPORT_ADDED_SUCCESSFULLY"
# REPORT_TYPE_LISTED_SUCCESSFULLY = "REPORT_TYPE_LISTED_SUCCESSFULLY"
# REPORT_FREQUENCY_LISTED_SUCCESSFULLY = "REPORT_FREQUENCY_LISTED_SUCCESSFULLY"
# REPORT_DELETED_SUCCESSFULLY = "REPORT_DELETED_SUCCESSFULLY"
# REPORT_UPDATED_SUCCESSFULLY = "REPORT_UPDATED_SUCCESSFULLY"
# REPORT_RETRIEVED_SUCCESSFULLY = "REPORT_RETRIEVED_SUCCESSFULLY"

# # FirmwareUpgrade
# FILE_UPLOADED_SUCCESSFULLY = "FILE_UPLOADED_SUCCESSFULLY"
# FIRMWARE_UPGRADE_WITH_ERRORS = 'FIRMWARE_UPGRADE_INITIATED_WITH_ERRORS'
# FIRMWARE_UPGRADE_SUCCESSFUL = 'FIRMWARE_UPGRADE_INITIATED_SUCCESSFULLY'
# CANNOT_DELETE_ZTP_FIRMWARE = "CANNOT_DELETE_ZTP_FIRMWARE"
# FIRMWARE_DELETED_SUCCESSFULLY = 'FIRMWARE_DELETED_SUCCESSFULLY'
# FIRMWARE_DELETED_WITH_ERRORS = 'FIRMWARE_DELETED_WITH_ERRORS'
# FIRMWARE_ALREADY_EXISTS = 'FIRMWARE_FILE_ALREADY_EXISTS'
# # ScheduledFirmwareUpgrade
# FIRMWARE_SCHEDULED_SUCCESSFULLY = 'FIRMWARE_SCHEDULED_SUCCESSFULLY'
# FIRMWARE_SCHEDULE_ERROR = 'FIRMWARE_SCHEDULE_ERROR'
# SCHEDULE_TIME_FOR_FIRMWARE = 'SCHEDULE_TIME_FOR_FIRMWARE'
# NO_SCHEDULER_FOUND_FOR_FIRMWARE = 'NO_SCHEDULER_FOUND_FOR_FIRMWARE'
# EXCEPTION_OCCURED_WHILE_FIRMWARE_UPGRADE = 'EXCEPTION_OCCURED_WHILE_FIRMWARE_UPGRADE'
# NO_LATEST_FIRMWARE_FOUND = 'NO_LATEST_FIRMWARE_FOUND'
# AP_ALREADY_ON_LATEST_FIRMWARE = 'AP_ALREADY_ON_LATEST_FIRMWARE'
# LATEST_FIRMWARE_AVAILABLE = 'LATEST_FIRMWARE_AVAILABLE'
# DEVICE_ALREADY_ON_THE_LATEST_VERSION ='DEVICE_ALREADY_ON_THE_LATEST_VERSION'
# # ScheduledConfigurationUpgrade
# CONFIGURATION_SCHEDULED_SUCCESSFULLY = 'CONFIGURATION_SCHEDULED_SUCCESSFULLY'
# CONFIGURATION_RESCHEDULED_SUCCESSFULLY = 'CONFIGURATION_RESCHEDULED_SUCCESSFULLY'
# CONFIGURATION_LISTED_SUCCESSFULLY = 'CONFIGURATION_LISTED_SUCCESSFULLY'
# CONFIGURATION_DELETED_SUCCESSFULLY = 'CONFIGURATION DELETED SUCCESSFULLY'
# CONFIGURATION_SCHEDULE_ERROR = 'CONFIGURATION_SCHEDULE_ERROR'
# SCHEDULE_TIME_FOR_CONFIGURATION = 'SCHEDULE_TIME_FOR_CONFIGURATION'
# NO_SCHEDULER_FOUND_FOR_CONFIGURATION = 'NO_SCHEDULER_FOUND_FOR_CONFIGURATION'
# EXCEPTION_OCCURRED_WHILE_CONFIGURATION_UPGRADE = 'EXCEPTION_OCCURRED_WHILE_CONFIGURATION_UPGRADE'
# NO_LATEST_CONFIGURATION_FOUND = 'NO_LATEST_CONFIGURATION_FOUND'
# AP_ALREADY_ON_LATEST_CONFIGURATION = 'AP_ALREADY_ON_LATEST_CONFIGURATION'
# LATEST_CONFIGURATION_AVAILABLE = 'LATEST_CONFIGURATION_AVAILABLE'
# DEVICE_ALREADY_ON_THE_LATEST_VERSION ='DEVICE_ALREADY_ON_THE_LATEST_VERSION'

# # Backup & Restore
# BACKUP_DOES_EXISTS = "BACKUP_DOES_EXISTS"
# FULL_BACKUP_CREATED = 'Added Full cNMS Backup "{backup_name}"'
# BACKUP_CREATED_SUCCESSFULLY = "BACKUP_CREATED_SUCCESSFULLY"
# BACKUP_INITIATED_SUCCESSFULLY = "BACKUP_INITIATED_SUCCESSFULLY"
# BACKUP_RESTORED_SUCCESSFULLY = "BACKUP_RESTORED_SUCCESSFULLY"
# BACKUP_DELETED_SUCCESSFULLY = "BACKUP_DELETED_SUCCESSFULLY"
# DEVICE_BACKUP_CREATED_SUCCESSFULLY = "DEVICE_BACKUP_CREATED_SUCCESSFULLY"
# DEVICE_BACKUP_INITIATED_SUCCESSFULLY = "DEVICE_BACKUP_INITIATED_SUCCESSFULLY"
# DEVICE_BACKUP_RESTORED_SUCCESSFULLY = "DEVICE_BACKUP_RESTORED_SUCCESSFULLY"
# DEVICE_BACKUP_DELETED_SUCCESSFULLY = "DEVICE_BACKUP_DELETED_SUCCESSFULLY"
# DEVICE_REPLACEMENT_CREATED_SUCCESSFULLY = "DEVICE_REPLACEMENT_CREATED_SUCCESSFULLY"


# # Troubleshooting
# PING_REQUEST_STARTED = "PING_REQUEST_STARTED"
# TRACE_REQUEST_STARTED = "TRACE_REQUEST_STARTED"
# ERROR_IN_PING_TRACE_ROUTE = "ERROR_IN_PING_TRACE_ROUTE"

# # Global MAC ACL
# MAC_ACL_NAME_EXISTS = 'GLOBAL_MAC_ACL_NAME_EXISTS'
# CONFIGURATION_SCHEDULE_ERR = 'CONFIGURATION_SCHEDULE_ERR'
# # Global Radius Server
# RADIUS_NAME_EXISTS = 'AAA_SERVER_NAME_EXISTS_IN_OTHER_TENANT'

# # Extension Channel MApper
# EXTENSION_CHANNEL_LISTED_SUCCESSFULLY = 'EXTENSION_LISTED_SUCCESSFULLY'

# # Auto RF
# CHANNEL_UTILIZATION_RETRIEVED_SUCCESSFULLY = "CHANNEL_UTILIZATION_RETRIEVED_SUCCESSFULLY"
# CHANNEL_INFO_RETRIEVED_SUCCESSFULLY = "CHANNEL_INFO_RETRIEVED_SUCCESSFULLY"

# # License
# LICENSE_UPLOADED_SUCCESSFULLY ="LICENSE_UPLOADED_SUCCESSFULLY"

# # Tenant
# EMAIL_USED_BY_TENANT = "EMAIL_ALREADY_USED_BY_OTHER_TENANT"
# PHONE_USED_BY_TENANT = "PHONE_ALREADY_USED_BY_OTHER_TENANT"
# TIME_ZONE_LISTED_SUCCESSFULLY = "TIME_ZONE_LISTED_SUCCESSFULLY"

# #NodeHealthCheck
# NODE_STATUS_LISTED_SUCCESSFULLY = "NODE_STATUS_LISTED_SUCCESSFULLY"
# ERROR_IN_LISTING_THE_NODE_STATUS = "ERROR_IN_LISTING_THE_NODE_STATUS"

# #UBR
# UBR_ADDED_SUCCESSFULLY="UBR_ADDED_SUCCESSFULLY"
# UBR_DELETED_SUCCESSFULLY="UBR_DELETION_INITIATED_SUCCESSFULLY"
# UBR_LISTED_SUCCESSFULLY = 'UBR_LISTED_SUCCESSFULLY'
# UBR_CONFIG_UPDATED_SUCCESSFULLY = "UBR_CONFIG_UPDATED_SUCCESSFULLY"
# UBR_RADIO_UPDATED_SUCCESSFULLY = "UBR_RADIO_UPDATED_SUCCESSFULLY"
# UBR_TDMA_CONFIG_LISTED_SUCCESSFULLY = "UBR_TDMA_CONFIG_LISTED_SUCCESSFULLY"
# UBR_BASIC_NTP_CONFIG_UPDATED_SUCCESSFULLY = "UBR_BASIC_NTP_CONFIG_UPDATED_SUCCESSFULLY"
# UBR_JUMBO_CONFIG_UPDATED_SUCCESSFULLY = "UBR_JUMBO_CONFIG_UPDATED_SUCCESSFULLY"
# UBR_DEVICE_GUI_CONFIG_UPDATED_SUCCESSFULLY = "UBR_DEVICE_GUI_CONFIG_UPDATED_SUCCESSFULLY"
# UBR_DEVICE_PASSWORD_CONFIG_UPDATED_SUCCESSFULLY = "UBR_DEVICE_PASSWORD_CONFIG_UPDATED_SUCCESSFULLY"
# DEVICE_LIST_EXCEPTION = 'Exception occurred while fetching device list'
# DEVICE_DOES_NOT_EXIST = 'Device Does Not Exist'
# UBR_DEVICE_REBOOTED_SUCCESSFULLY = 'UBR_DEVICE_REBOOTED_SUCCESSFULLY'
# UBR_DEVICE_FACTORY_RESET_SUCCESSFUL = 'UBR_DEVICE_FACTORY_RESET_SUCCESSFUL'
# TIMEZONE_LISTED = 'COUNTRY TIMEZONE LISTED SUCCESSFULLY'
# TIMEZONE_LIST_EXCEPTION = "COUNTRY TIMEZONE EXCEPTION"

# # UBR ATPC
# UBR_ATPC_CONFIGURATION_LISTED = "UBR_ATPC Configuration listed successfully"
# UBR_ATPC_CONFIGURATION_LIST_ERROR = "UBR Error while listing the ATPC data"
# UBR_ATPC_CONFIGURATION_UPDATED = "UBR ATPC Configuration Data updated successfully"
# UBR_ATPC_CONFIGURATION_UPDATE_EXCEPTION = "UBR Eror while updating the ATPC data"
# UBR_UPDATED_SUCCESSFULLY="UBR_UPDATED_SUCCESSFULLY"
# UBR_RETRIEVED_SUCCESSFULLY="UBR_RETRIEVED_SUCCESSFULLY"

# #Link
# LINK_ADDED = "LINK_ADDED"
# IS_REQUIRED_FIELD = "IS_REQUIRED_FIELD"
# LINK_DELETED_WITH_ERRORS = "LINK_DELETED_WITH_ERRORS"
# LINK_DELETED_SUCCESSFULLY = "LINK_DELETED_SUCCESSFULLY"
# LINK_LISTED_SUCCESSFULLY = "LINK_LISTED_SUCCESSFULLY"
# TDMA_FOR_LINK_LISTED_SUCCESSFULLY = "TDMA_FOR_LINK_LISTED_SUCCESSFULLY"
# LINK_MOVED_SUCCESSFULLY = "LINK_MOVED_SUCCESSFULLY"
# TDMA_RETRIEVED_SUCCESSFULLY = "TDMA_RETRIEVED_SUCCESSFULLY"
# TDMA_RETRIEVE_EXCEPTION = 'Exception occured while retrieving TDMA'
# RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND'

# #Link Group
# LINK_GROUP_LISTED_SUCCESSFULLY = "LINK_GROUP_LISTED_SUCCESSFULLY"
# LINK_GROUP_ADDED_SUCCESSFULLY = "LINK_GROUP_ADDED_SUCCESSFULLY"
# LINK_GROUP_DELETED_WITH_ERRORS = "LINK_GROUP_DELETED_WITH_ERRORS"
# LINK_GROUP_DELETED_SUCCESSFULLY = "LINK_GROUP_DELETED_SUCCESSFULLY"
# LINK_GROUP_UPDATED_SUCCESSFULLY = "LINK_GROUP_UPDATED_SUCCESSFULLY"
# LINK_MOVED_SUCCESSFULLY_WITH_ERRORS = "LINK_MOVED_SUCCESSFULLY_WITH_ERRORS"
# LINK_MERGED_SUCCESSFULLY = "LINK_MERGED_SUCCESSFULLY"
# LINK_CANNOT_BE_MERGED = "LINK_CANNOT_BE_MERGED"

# #Link Associated to group
# LINK_ASSOCIATED_TO_GROUP_LISTED_SUCCESSFULLY = "LINK_ASSOCIATED_TO_GROUP_LISTED_SUCCESSFULLY"


# #UBR Alarm report
# UBR_REPORT_TYPE_LISTED_SUCCESSFULLY = "UBR_REPORT_TYPE_LISTED_SUCCESSFULLY"
# UBR_ALARM_REPORT_ADDED_SUCCESSFULLY = "UBR_ALARM_REPORT_ADDED_SUCCESSFULLY"
# UBR_ALARM_REPORT_LISTED_SUCCESSFULLY = "UBR_ALARM_REPORT_LISTED_SUCCESSFULLY"
# UBR_ALARM_REPORT_DELETED_SUCCESSFULLY = "UBR_ALARM_REPORT_DELETED_SUCCESSFULLY"
# UBR_ALARM_REPORT_UPDATED_SUCCESSFULLY = "UBR_ALARM_REPORT_UPDATED_SUCCESSFULLY"
# UBR_ALARM_REPORT_RETRIEVED_SUCCESSFULLY = "UBR_ALARM_REPORT_RETRIEVED_SUCCESSFULLY"
# UBR_HISTORICAL_ALARM_REPORT_LISTED_SUCCESSFULLY = "UBR_HISTORICAL_ALARM_REPORT_LISTED_SUCCESSFULLY"
# UBR_DAILY_INVENTORY_REPORT_LISTED_SUCCESSFULLY = "UBR_DAILY_INVENTORY_REPORT_LISTED_SUCCESSFULLY"
# UBR_HOURLY_INVENTORY_REPORT_LISTED_SUCCESSFULLY = "UBR_HOURLY_INVENTORY_REPORT_LISTED_SUCCESSFULLY"

# #Troubleshooting
# JSON_PUBLISHED_SUCCESSFULLY_TO_DEVICES = 'Json published successfully to devices'
# JSON_PUBLISHED_TO_PARTIAL_DEVICES = 'Json published to partial devices'
# SERIAL_NOS_NOT_PRESENT_IN_CNMS = 'Serial nos. not present in cnms'
# SERIAL_NO_CONVERTED_TO_QUEUE_SUCCESSFULLY = 'Serial no. converted to queue successfully'
# QUEUE_CONVERTED_TO_SERIAL_NO_SUCCESSFULLY = 'Queue converted to serial no. successfully'
# ALARM_CONVERTED_SUCCESSFULLY = 'Alarm converted successfully'

# """